# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. We will try and get back to you as soon as possible.

  Please make sure that you followed the issue template, and provided all neccessary information.
  Failure to do so will prevent us from resolving the issue in a timely manner. 
  
  Please note that suggestions are now to be submitted to https://git.io/fN5B4 rather than this issue tracker!
