name: ${name}
main: com.github.intellectualsites.plotsquared.bukkit.BukkitMain
api-version: "1.13"
version: "${version}"
load: STARTUP
description: >
             Easy, yet powerful Plot World generation and management.
authors: [Citymonstret, Empire92, MattBDev, dordsor21]
website: https://github.com/IntellectualSites/
softdepend: [BarAPI, CameraAPI, Vault]
loadbefore: [MultiWorld, Multiverse-Core]
depend: [WorldEdit]
database: false
commands:
  plots:
    description: Plot command.
    aliases: [p,plot,ps,plotsquared,p2,2,plotme]
    permission: plots.use
    permission-message: "You are lacking the permission node 'plots.use'"
permissions:
  plots.use:
    default: true
  plots.permpack.basicflags:
    default: op
    children:
      plots.set.flag: true
      plots.flag: true
      plots.flag.add: true
      plots.flag.remove: true
      plots.flag.list: true
      plots.flag.info: true
      plots.set.flag.titles.*: true
      plots.set.flag.greeting.*: true
      plots.set.flag.farewell.*: true
      plots.set.flag.notify-enter.*: true
      plots.set.flag.notify-leave.*: true
      plots.set.flag.feed.*: true
      plots.set.flag.heal.*: true
      plots.set.flag.invincible.*: true
      plots.set.flag.instabreak.*: true
      plots.set.flag.fly.*: true
      plots.set.flag.gamemode: true
      plots.set.flag.gamemode.creative: true
      plots.set.flag.gamemode.survival: true
      plots.set.flag.gamemode.adventure: true
      plots.set.flag.time.*: true
      plots.set.flag.weather.*: true
      plots.set.flag.music.*: true
      plots.set.flag.disable-physics.*: true
      plots.set.flag.pve.*: true
      plots.set.flag.pvp.*: true
      plots.set.flag.explosion.*: true
      plots.set.flag.hostile-interact.*: true
      plots.set.flag.hostile-attack.*: true
      plots.set.flag.player-interact.*: true
      plots.set.flag.animal-interact.*: true
      plots.set.flag.animal-attack.*: true
      plots.set.flag.tamed-interact.*: true
      plots.set.flag.tamed-attack.*: true
      plots.set.flag.misc-interact.*: true
      plots.set.flag.hanging-place.*: true
      plots.set.flag.hanging-break.*: true
      plots.set.flag.vehicle-use.*: true
      plots.set.flag.vehicle-place.*: true
      plots.set.flag.vehicle-break.*: true
      plots.set.flag.place.*: true
      plots.set.flag.break.*: true
      plots.set.flag.use.*: true
      plots.set.flag.forcefield.*: true
      plots.set.flag.price.*: true
      plots.set.flag.no-worldedit.*: true
  plots.permpack.basicinbox:
    default: op
    children:
      comments.notifications.enabled: true
      plots.inbox.read.public: true
      plots.inbox.modify.public: true
      plots.inbox.write.public: true
      plots.inbox.read.report: true
      plots.inbox.write.report: true
      plots.inbox.read.owner: true
      plots.inbox.modify.owner: true
      plots.inbox.write.owner: true
      plots.comment: true
      plots.inbox: true
  plots.permpack.wilderness:
    default: op
    children:
      plots.admin.interact.unowned: true
      plots.admin.destroy.unowned: true
      plots.admin.build.unowned: true
      plots.projectile.unowned: true
      plots.admin.vehicle.break.unowned: true
      plots.admin.pve.unowned: true
  plots.permpack.basic:
    default: op
    children:
      plots.use: true
      plots.info: true
      plots.claim: true
      plots.auto: true
      plots.home: true
      plots.clear: true
      plots.delete: true
      plots.music: true
      plots.list: true
      plots.list.mine: true
      plots.list.shared: true
      plots.list.world: true
      plots.list.all: true
      plots.list.forsale: true
      plots.list.unowned: true
      plots.list.unknown: true
      plots.set: true
      plots.visit: true
      plots.visit.owned: true
      plots.visit.shared: true
      plots.set.flag: true
      plots.flag.add: true
      plots.flag.remove: true
      plots.flag.list: true
      plots.flag.info: true
      plots.flag: true
      plots.buy: true
      plots.chat: true
      plots.confirm: true
      plots.toggle: true
      plots.toggle.titles: true
      plots.toggle.chat: true
      plots.toggle.time: true
      plots.set.biome: true
      plots.set.home: true
      plots.set.alias: true
      plots.alias.set: true
      plots.alias.remove: true
      plots.set.description: true
      plots.description: true
      plots.alias: true
      plots.merge: true
      plots.merge.other: true
      plots.merge.4: true
      plots.unlink: true
      plots.denied: true
      plots.add: true
      plots.trust: true
      plots.deny: true
      plots.remove: true
      plots.untrust: true
      plots.undeny: true
      plots.kick: true
      plots.download: true
      plots.save: true
      plots.done: true
      plots.continue: true
      plots.middle: true
  plots.worldedit.bypass:
    default: false
  plots.gamemode.bypass:
    default: op
  plots.confirm.bypass:
    default: false
  plotme.use:
    description: Gives default user commands
    children:
      plots.permpack.basic: true
      plots.plot.1: true
  plotme.admin:
    description: Gives default administrator commands
    children:
      plots.admin: true
  plotme.use.middle:
    children:
      plots.middle: true
  plotme.use.buy:
    children:
      plots.buy: true
  plotme.use.sell:
    children:
      plots.set: true
      plots.flag: true
      plots.set.flag: true
      plots.set.price.*: true
  plotme.use.dispose:
    children:
      plots.delete: true
  plotme.use.done:
    children:
      plots.done: true
  plotme.use.claim:
    children:
      plots.claim: true
  plotme.use.auto:
    children:
      plots.auto: true
  plotme.use.reset:
    children:
      plots.delete: true
  plotme.use.home:
    children:
      plots.home: true
  plotme.use.info:
    children:
      plots.info: true
  plotme.use.biome:
    children:
      plots.set: true
      plots.set.biome: true
  plotme.use.clear:
    children:
      plots.clear: true
  plotme.use.list:
    children:
      plots.list: true
      plots.list.forsale: true
      plots.list.mine: true
      plots.list.shared: true
  plotme.use.add:
    children:
      plots.add: true
      plots.trust: true
      plots.add.everyone: true
      plots.trust.everyone: true
  plotme.use.deny:
    children:
      plots.deny: true
      plots.deny.everyone: true
  plotme.use.remove:
    children:
      plots.remove: true
  plotme.use.undeny:
    children:
      plots.remove: true
  plotme.use.protect:
    children:
      plots.set: true
      plots.flag: true
      plots.set.flag: true
      plots.set.keep.*: true
  plotme.use.nameplot:
    children:
      plots.set.alias: true
      plots.alias.set: true
      plots.alias.remove: true
  plotme.limit.*:
    children:
      plots.plot.*: true
  plotme.limit.1:
    children:
      plots.plot.1: true
  plotme.limit.5:
    children:
      plots.plot.5: true
  plotme.limit.10:
    children:
      plots.plot.10: true
  plotme.admin.clear:
    children:
      plots.admin.command.clear: true
  plotme.admin.reset:
    children:
      plots.admin.command.delete: true
  plotme.admin.add:
    children:
      plots.admin.command.add: true
  plotme.admin.deny:
    children:
      plots.admin.command.deny: true
  plotme.admin.remove:
    children:
      plots.admin.command.remove: true
  plotme.admin.undeny:
    children:
      plots.admin.command.remove: true
  plotme.admin.bypassdeny:
    children:
      plots.admin.entry.denied: true
  plotme.admin.setowner:
    children:
      plots.admin.command.setowner: true
  plotme.admin.move:
    children:
      plots.admin.command.move: true
  plotme.admin.weanywhere:
    children:
      plots.worldedit.bypass: true
  plotme.admin.list:
    children:
      plots.list.world: true
      plots.list.world.*: true
      plots.list.top: true
      plots.list.all: true
      plots.list.unowned: true
      plots.list.unknown: true
      plots.list.player: true
      plots.list.done: true
      plots.list.expired: true
      plots.list.fuzzy: true
      plots.list.area: true
  plotme.admin.dispose:
    children:
      plots.admin.command.delete: true
  plotme.admin.done:
    children:
      plots.admin.command.done: true
  plotme.admin.expired:
    children:
      plots.list.expired: true
  plotme.admin.buildanywhere:
    children:
      plots.admin.vehicle.*: true
      plots.admin.interact.*: true
      plots.admin.build.*: true
      plots.admin.destroy.*: true
